---
output: html_document
---

</b></br>
</b></br>

> Publications


1. Baker, D; **Lopez, E.** & Greenlee, A. (2021) “An Ex-Ante model to estimate the displacement cost from Transit Oriented Developments” CITIES, Vol. 115. | [paper](https://doi.org/10.1016/j.cities.2021.103212) | [Slides](docs/slides/TOD&HousingDisplacement_NARSC2019.pdf)   | [twitter thread](https://twitter.com/elopez8a/status/1387884163085312007?s=20)
<details>
        <summary>Abstract</summary>
  Chicago's South Side has long been characterized as a “transit desert” – an area with high transit inaccessibility and insufficient infrastructure to meet residents' needs (Jiao & Dillivan, 2013). Without adequate transit, residents cannot reach employment opportunities or regional amenities – contributing to economic, spatial, and social marginalization. The Chicago Transit Authority's proposed Red Line Extension (RLE) is designed to connect the city's far south side neighborhoods to Chicago's core. Given the scope of the RLE, 175 parcels have been chosen for demolition, meaning that a similar number of households face displacement to make room for the RLE right of way – which may have potentially negative consequences in realizing the subsequent benefits of improved transit access. In this article, we perform an ex-ante analysis of RLE induced displacement. Specifically, we: 1) predict potential location choices that transit displacees are most likely to choose; and 2) analyze these locations in relation to access to transit, amenities, employment, and housing affordability, among others. Within the context of transportation planning, ex-ante analysis is important because it can minimize unintended and negative consequences of transit-induced displacement – like decreased transit access and a loss of potential neighborhood improvements - by predicting potential relocation choices for displacees. Such predicted choices can help planners and decision-makers better understand the trade-offs for directly affected households and thereby allow planners and decision-makers to assist in relocation assistance that maximizes the benefits of the necessarily displaced.
</details>

</b></br>


2. Backman, M., **Lopez, E.** & Rowe, F. (2020) “*Revealing Migrant pathways in the formal labor market: The case of Sweden*”. **Journal of Small Business Economics.56,963–983** | [Paper](https://doi.org/10.1007/s11187-019-00312-z)  |   [twitter thread](https://twitter.com/elopez8a/status/1364579087625388032?s=20)
<details>
  <summary>Abstract</summary>
The current surge in forced migration to Europe is probably the largest and most complex since the Second World War. As population aging accelerates and fertility falls below replacement level, immigration may be seen as a key component of human capital to address labor and skill shortages. Receiving countries are, however, hesitant about the contribution that forced migrants can make to the local economy. Coupled with increasing pressure on welfare services, they are associated with increased job competition and crime. Underutilization of immigrants’ skills is, however, a waste of resources that countries can scarcely afford. Understanding the labor market integration process of forced migrants is thus critical to develop policies that unleash their full skills potential and ultimately foster local economic productivity. While prior studies have examined the employment and salary outcomes of these immigrants at a particular point in time post-migration, they have failed to capture the temporal dynamics and complexity of this process. Drawing on administrative data from Sweden, we examine the occupational pathways of forced migrants using sequence analysis from their arrival in 1991 through to 2013. Findings reveal polarized pathways of long-term labor market integration with over one-third of refugees experiencing a successful labor market integration pathway and an equally large share facing a less fruitful employment outcomes. Our findings suggest education provision is key to promote a more successful integration into the local labor market by reducing barriers of cultural proximity and increasing the occurrence of entrepreneurship activity.
</details>

</b></br>

3. Bonilla, L., **Lopez, E.** & McMillen, D. (2019) “*House Prices and School Choice: Evidence from the Chicago’s Magnet Schools Proximity Lottery*”. **Journal of Regional Science**. [Paper](https://doi.org/10.1111/jors.12447)  |  [Slides](docs/slides/ELopez_MSACE_Slides.pdf) | [twitter thread](https://twitter.com/elopez8a/status/1130855683203579904?s=20) | [poster](docs/slides/Lopez,Bonilla&McMillen_final.ppt) | [award](docs/slides/NARSC-SLPA-Elopez.pdf)
<details>
  <summary>Abstract</summary>
Studies of open school policies predict house prices to rise in areas that gain access to high-quality schools. However, excess demand may limit access to high-quality schools. We take advantage of changes in Chicago's schools’ admissions policies to test whether a higher probability of admission to magnet schools for students living within 1.5 miles leads to higher house prices. Results indicate that the 1997 and 2009 reforms increased house prices for homes within the 1.5 mile radius by about 4% and 12.6%, respectively. The higher probability of admission for black students after a consent decree was vacated in 2009 led to a significant increase in prices in predominantly African-American areas on the south side.
</details>

</b></br>

4. **Lopez, E.** & Hewings G. (2018) “*Housing Price Indices for Small Spatial Units*” **Regional Science and Urban Economics**, Vol. 70, 57-71. [Paper](https://doi.org/10.1016/j.regsciurbeco.2018.02.005)  |  [slides](docs/slides/HousingPriceIndices.pdf) | _research funded by the Illinois Realtor Association_
<details>
  <summary>Abstract</summary>
Median-based Housing Price Indices (HPIs) generate potentially misleading indicators especially when applied to Small Spatial Units (SSUs) such as small Metropolitan Statistical Areas (MSAs) or neighborhoods within larger metropolitan regions. Given the small total number of sales in SSUs and the even smaller number of repeat sales, traditional alternatives are few. A matching-based Fisher HPI is proposed as an alternative that provides more accurate estimations for SSUs given that it both controls for housing characteristics and is not restricted just to repeated sales. This paper makes use of housing sales data from the state of Illinois, as an example of the application of the methodology to small MSAs and at the neighborhood level within larger MSAs. The results highlight some of the biases that have arisen from the use of median price indicators.
</details>

</b></br>

5. **Lopez, E.** & Paredes, D. (2018) “*Towards Housing Policies that Consider Households’ Preferences: Estimating the Demand for Housing Attributes in Chile*”. **International Journal of Strategic and Property Management**. Vol. 22(1), 24-36.[Paper](https://doi.org/10.3846/ijspm.2018.320)  |  [slides](docs/slides/HousingDemandChile_LincolnInst.pdf) |  _funded by the Lincoln Institute of Land Policy (30K)_
<details>
  <summary>Abstract</summary>
Understanding household preferences for housing attributes is imperative for developing countries after years of housing policies that failed mostly due to the mismatch between housing solutions and needs. This paper provides income and price elasticity estimates of the demand for housing attributes as an indicator to measure how households perceive housing attributes (necessities or luxuries). These metrics are important because they allow evaluating previously national-level housing policies as well as suggesting new paths of action that are in accordance to households’ preferences. The study focuses on Chile because its influential role in designing housing policies in other developing countries (Gilbert, 2002). Using five cross-section household surveys from 2000–2011, our results suggest that Size and Location are perceived as basic necessities. Contrarily, Quality and Housing Features are considered luxury goods. Size and Location are more price-inelastic than other attributes. These results are consistent across regions, and suggest that households prefer larger and better-located houses.
</details>

</b></br>


6. Kleasson, J. **Lopez, E.** & Öner, Ö. (2018) “*Estimating the wage premium of delayed retirement and its variations across space*” **Tijdschrift voor economische en sociale geografie**, Vol. 109 (3) 350-370. [Paper](http://onlinelibrary.wiley.com/doi/10.1111/tesg.12295/full)  |  [slides](docs/slides/Klaesson, Lopez & Oner.pdf)
<details>
  <summary>Abstract</summary>
Who works longer – and why? This paper investigates the characteristics of people that stay longer in the workforce, even beyond the time they are eligible to retire. In our regional analysis, we use an 11-year balanced panel of 290 Swedish regions. In the individual analysis, we use a large individual level panel to apply Cox proportional hazard estimates on ‘risk’ of entering retirement. Our results show a large gender difference: women tend to retire earlier than men. Between employees and entrepreneurs, entrepreneurs retire later. People in larger regions tend to retire later. Higher house prices, and the share of small firms in a region correlate with a lower likelihood of retirement. The local tax rate and the share of blue-collar workers in a region is significantly related to lower retirement age. A high average wage, commuting intensity, and high human capital in a region is associated with later retirement
</details>

</b></br>

7. **Lopez, E.** & Greenlee, A. (2016) “*Residential Mobility and Location Choice as the Product of Housing Displacement: An ex ante Analysis*”. **Applied Geography**, Vol. 75, 156-175. [Paper](https://doi.org/10.1016/j.apgeog.2016.08.013)  |  [slides](docs/slides/ResidentialMobility-WRSA2016.pdf)
<details>
  <summary>Abstract</summary>
Urban renewal has been criticized for its unintended effects on the displacement of residents to housing situations where they are worse off. The literature concerned with housing displacement focuses on after the fact (ex post) analysis of mobility, hence providing only partial insights to prospective outcomes for residents. In this article, we develop a methodology for predicting before the fact (ex ante) spatial location outcomes for residents facing forced displacement. We ask where in the city will displaced residents locate and how do potential new locations compare to the current one? We apply this methodology to an ongoing urban renewal project in Illinois in order to predict spatial relocation patterns. Our findings show that residents facing forced displacement are likely to relocate to low-priced neighborhoods that are on average as bad or worse off in terms of housing adequacy, accessibility to labor, and shopping. These findings not only bear important implications for urban redevelopment policy, but also help to reveal spatially determined costs of moving which are not factored into current redevelopment impact evaluations.
</details>

</b></br>

8. **Lopez, E.** & Aroca, P. (2012) “*Estimación de la inflación regional de los precios de la vivienda en Chile*”. **Trimestre Económico**, Vol. 79 (315), 601-630. [Paper](https://www.jstor.org/stable/23349530)  |  [slides](docs/slides/Estimacion de la Inflacion Regional de los Precios de la Vivienda.pdf)
<details>
  <summary>Abstract</summary>
La inflación ha sido permanentemente estudiada en Chile por sus efectos negativos en la economía; sin embargo su investigación es escasa por región, porque ha primado el supuesto de que las economías regionales tienen un comportamiento homogéneo respecto a la inflación. Extendiendo la metodología de Paredes y Aroca (2008) al plano temporal y utilizando información de inflación nacional producida por el Instituto Nacional de Estadísticas, este artículo contribuye con una estimación de la inflación de los precios de las viviendas de las regiones chilenas. Los resultados sugieren que las regiones además de tener distintos costos de vida (más altos para las regiones extremas que para las del centro), muestran una evolución con velocidades diferentes. Esto sugiere que la elaboración de políticas habitacionales (y potencialmente en todos los sectores) destinadas a reducir la inflación tengan efectos heterogéneos en el territorio y sean menos eficaces de las que podrían formularse considerando las diferencias inflacionarias entre las regiones. Inflation has been constantly studied at national level because its negative effects over the economy, however this problem has generally been ignored at regional scale, mainly because the assumption that regions have a homogeneous inflation behavior. Expanding the Paredes and Aroca (2008) methodology to the temporal dimension and using National Statistics Institute (INE) data, this paper contributes with an estimation of regional housing inflation for Chilean regions. Main results suggest that regions besides bear different cost of living (higher for extreme regions than those in the center), are also showing heterogeneous speed in their price evolution process. This result suggests that effects of housing policies (and potentially other sectors policies) are heterogeneous between regions and more inefficient than those that could be implemented when taking account of the different regional inflation pattern.
</details>

</b></br>


> Working Papers

+ "Housing price indices from on-line data: addressing spatial posting bias with sampling weights"
+ "Covid-19 and employment relief programs: A tale of spatially blind policies, for a spatially driven pandemic" with Patricio Aroca and Juan Eberhard. **Revise and Resubmit** in the Journal of Regional Science
+ "The effect of commuting on school performance: Evidence from a country-wide school reform" with Rocío Valdebenito (UIUC) and Patricio Aroca (UAI). Preparing for resubmission

> Research in Progress

+ "Measuring congestion costs between and within cities: the case of Chile" with Felipe Morales and Patricio Aroca (UAI).
+ "When green production yields poverty: The socioeconomic effects of forestry expansion in Chile” with Leonardo Bonilla (Central Bank of Colombia.)
+ "Estimating the spatial distribution of firm power and its effects on regional migration" with Mikaela Backman (Jönköping University, Sweden).

